### ISSUE TITLE
Should check if "githubSearchUrl" not null to avoid null pointer exception

### ISSUE THREAD

**Issue by ionutincau** [MariusDK/T02.03-Exercise-DisplayUrl#1]
https://github.com/MariusDK/T02.03-Exercise-DisplayUrl/blob/df61f978e5c13ad6cbd54a05c1f61acbd5185efa/app/src/main/java/com/example/android/datafrominternet/MainActivity.java#L57

**Comment by MariusDK** [comment]
I saw in the log and I will take care of it.
It's part of the exercise to get this error.
